### PR TITLE
Issue #24 SetText(CharSequence text) method passing empty string 

### PR DESCRIPTION
**Pull request by rbiresch**
Here's a fix for clearing the text ( setText(null) or setText("") ).

### CODE REVIEW

**Comment by BlacKCaT27** [comment]
Hey there!

sorry for the super delayed response.

I just released v2.0 of the library but still need to get this fix merged in. 

Rather than merge this right into master (a bad habit I'm trying to get myself out of), could you retarget this pull request to 'next'? Then I'll pull it in and give it a once-over before merging it into the main branch when I get a few other bugs worked out.

**Comment by rbiresch** [comment]
I've updated my branch with all your changes. I could not test because I'm not running Android Studio 3.0

> Error:This Gradle plugin requires Studio 3.0 minimum

It should get you close enough.

**Comment by BlacKCaT27** [comment]
So I checked out your branch and there were a couple issues/bugs, some related to the merge, others probably just because you couldn't run the app to check things out. 

Rather than go through the night-long struggle of back-and-forth commits/PRs to get things squared away using an environment you don't have access to, would it be alright with you if I just manually add your updates to the main Next branch to close this one out?

**Comment by rbiresch** [comment]
Sure, that's fine with me. Thanks!

**Pull request closed without merging**
