### PR TITLE
Added get and setValue for double values

### PR DESCRIPTION
**Pull request by klutzer**

### CODE REVIEW

**Comment by BlacKCaT27** [comment]
I'm not entirely sure what to do with this, to be honest. 

The main reason everything in the library works on longs is to protect the integrity of the underlying raw value that the user inputs. The only time the decimal place is ever added is during formatting, where any sort of rounding errors that affect the end result only impact the view cosmetically; the underlying value is still intact. (In fact, it now occurs to me that we shouldn't be using division for the divider placement at all and should be placing it manually by looping from the end. I may take a look at that...)

If we expose the use of doubles in the API, this assumption of integrity no longer holds true. Floating point division introduces rounding errors, and while the likelihood of rounding errors at two digits is low, it's still a possibility. This could leave the actual value that the user input in an unstable state. 

Finally, your setValue() method could end up having problems if the caller passes in a double value with more decimal places than the currencys DefaultFractionDigits. Example:

Currency: USD
Fraction Digits: 2

API input: 100.3425
result after calculations being passed to formatter: "10034".

You've now truncated off two digits of user input, and your value has diminished. 

You could address this by examining the passed in value and determining of the number of digits match those found in the currency to ensure they match, throwing an error otherwise. 


Is there a specific reason you're looking to add doubles to the API aside from convenience?

**Comment by klutzer** [comment]
I think it's more an easy way to set and get money values from the user. Of course the best way to handle money values is implementing the Money pattern (which isn't the component goal)..

Maybe we can use BigDecimal to avoid double rounding problems, holding the value as BigDecimal instead of long ('cause I think its more useful for the end application).

What do you think? (sorry for my english)

**Comment by klutzer** [comment]
Besides, if the currency is USD, for example, the user never will type an information with more than 2 decimals, right? It doesn't exists a value less than 0,01 for this currency

**Comment by BlacKCaT27** [comment]
First rule of programming: You can't make assumptions about user input. Ever. 

Secondly, this library supports multiple languages, some with more decimals as their lowest denomination than just the two used by USD. That's why all decimal work is done only for presentation, not calculation. There's no way to know the number of decimals to worry about at design time without some hacky solution like having the caller provide it, which breaks the entire purpose of this library (encapsulation of locality wrt currencies).

Keeping the numeric value stored as discrete units keeps us out of the realm of such edge cases, ensures rounding errors never become a problem, and keeps the solution uniform across all languages and currencies.

I'm sorry, but I don't feel that this PR is something that should be added to the library. Feel free to continue to use your fork if you feel otherwise.

Regardless, thank you for the PR. I do appreciate the effort to contributing, I just don't agree with the contents of this particular PR.

-Josh

**Comment by klutzer** [comment]
OK, When I said that user will never type an information with more than 2 decimals (in case of USD), I meant that own component don't allow this behavior, so technically it's not possible to insert "3.456" by typing in CurrencyEditText, right?

By the way, how do you suggest for developers that handle USD values to get and set currency with the library (assuming the use of any floating point type)?

**Comment by BlacKCaT27** [comment]
The owning component in that case is still considered "user input". As this is a library, called by arbitrary code, there can't be **any** assumptions made about what's coming into the API. And even though the CurrencyEditText view does enforce format, there's nothing stopping calling application code from taking the formatted result and then forcing it back into the API for some reason. Sure, that's not expected behavior, but designing for only the happy path is a fast track to failure.

The by-design method for handling any currency, not just USD, with CurrencyEditText is to use the getRawValue() method to return the actual input values entered by the user, and to treat that value as the monetary value in that currencies lowest available denomination. For example, "$10.00" shown in the CurrencyEditText view is represented by the long value 1000 from getRawValue. For setting values, simply call setText() as you would any other EditText view, giving a string value of a whole number, and the librarys formatter will handle the decimal placement. 

The library was designed to work with whole numbers to avoid the aforementioned rounding issues. If you're using floats/doubles in your app, your best bet will be to handle converting them to whole numbers yourself before providing them to a CurrencyEditText view.

**Comment by klutzer** [comment]
Right, I can do it by dividing the whole number returned in getRawValue() by 100 and then, to set back the value in CurrencyEditText, provide an String representation of long parsed value (which is doubleValue * 100). That's right? I just simplified that with the optional methods get and setValue..

**Comment by BlacKCaT27** [comment]
Yes, your approach is correct. The reason it's not going into the
CurrencyEditText library is that philosophically, I don't think that method
is the right approach for handling user input currency due to the decimal
division that takes place. If that's how your app is handling things, more
power to you and good luck. But I don't want to support that methodology in
CurrencyEditText.

On Sun, Jul 3, 2016 at 2:11 PM, Érico Knapp Lutzer <notifications@github.com

**Comment by klutzer** [comment]
Ok, I understand your concern..
Anyway, congrats and thanks for the great component!

**Pull request closed without merging**
